Netgen\Bundle\EzSyliusBundle\Entity\SyliusProduct:
    type: mappedSuperclass
    table: ngsyliusproduct
    id:
        contentId:
            type: integer
            column: contentobject_id
            id: true
    fields:
        productId:
            type: integer
            column: product_id
