{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default $attribute_base='ContentObjectAttribute'}

<input
    type="hidden"
    name="{$attribute_base}_data_product_id_{$attribute.id}"
    value="{$attribute.content.productId|wash}" />

<div class="block">
    <label>{'Product ID'|i18n( 'design/standard/content/datatype/syliusproduct' )}:</label>
    {if and($attribute.has_content, $attribute.content.productId|gt(0))}
        <p>{$attribute.content.productId|wash}</p>
    {else}
        <p>{'This object is not linked to any Sylius products'|i18n( 'design/standard/content/datatype/syliusproduct' )}</p>
    {/if}
</div>

<div class="block">
    <label>{'Code'|i18n('design/standard/content/datatype/syliusproduct')}: *</label>
    <input name="{$attribute_base}_data_code_{$attribute.id}"
        class="form-control"
        id="{$attribute_base}_data_code_{$attribute.id}"
        type="text"
        value="{$attribute.content.code|wash}" />
</div>

<div class="block">
    <label>{'Price'|i18n('design/standard/content/datatype/syliusproduct')}: *</label>
    <input name="{$attribute_base}_data_price_{$attribute.id}"
        class="form-control"
        id="{$attribute_base}_data_price_{$attribute.id}"
        type="number"
        value="{$attribute.content.price|wash}" />
</div>

<div class="block">
    <label>{'Name'|i18n('design/standard/content/datatype/syliusproduct')}: *</label>
    <input name="{$attribute_base}_data_name_{$attribute.id}"
        class="form-control"
        id="{$attribute_base}_data_name_{$attribute.id}"
        type="text"
        value="{$attribute.content.name|wash}" />
</div>

<div class="block">
    <label>{'Description'|i18n('design/standard/content/datatype/syliusproduct')}:</label>
    <textarea name="{$attribute_base}_data_description_{$attribute.id}"
        class="form-control"
        id="{$attribute_base}_data_description_{$attribute.id}"
        rows="10">{$attribute.content.description|wash}</textarea>
</div>

{/default}
