{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default $attribute_base='ContentObjectAttribute'}

<div class="block">
    <label>{'Product ID'|i18n( 'design/standard/content/datatype/syliusproduct' )}:</label>
    <input
        type="text"
        name="{$attribute_base}_data_product_id_{$attribute.id}"
        value="{if and($attribute.has_content, $attribute.content.productId|gt(0))}{$attribute.content.productId|wash}{/endif}" />
</div>

{/default}
